use pumpdb;

CREATE TABLE `Profile` (
	`PROFILE_ID` INT(6) NOT NULL AUTO_INCREMENT,
	`PROFILE_NAME` VARCHAR(3000),
    `IS_SELECTED` TINYINT(1),
	`CREATED_DATE` VARCHAR(20),
	`UPDATED_DATE` VARCHAR(20),
    `version` VARCHAR(5),
	PRIMARY KEY (`PROFILE_ID`)
);

CREATE TABLE `DAY` (
	`DAY_ID` INT(6) NOT NULL AUTO_INCREMENT,
	`OWNING_PROFILE` VARCHAR(20),
	`DAY_NAME` VARCHAR(20),
	`DAYTIMER_ID` INT(6) NOT NULL,
	PRIMARY KEY (`DAY_ID`)
);

CREATE TABLE `DAYTIMER` (
	`DAYTIMER_ID` INT(6) NOT NULL AUTO_INCREMENT,
	`TIMER_A1` VARCHAR(5),
	`TIMER_A2` VARCHAR(5),
	`TIMER_B1` VARCHAR(5),
	`TIMER_B2` VARCHAR(5),
	`TIMER_C1` VARCHAR(5),
	`TIMER_C2` VARCHAR(5),
	PRIMARY KEY (`DAYTIMER_ID`)
);

CREATE TABLE `ADDON` (
	`ADDON_ID` INT(6) NOT NULL,
	`OVERRIDE` VARCHAR(5),
	`SELECTED_NAME` VARCHAR(500),
	PRIMARY KEY (`ADDON_ID`)
);

CREATE TABLE `TOGGLE` (
	`TOGGLE_ID` INT(1) NOT NULL,
	`ISTOGGLE` BOOLEAN,
	PRIMARY KEY (`TOGGLE_ID`)
);